export const AIRPORTS = {
  // India
  DEL: { iata: 'DEL', name: 'Indira Gandhi Intl', city: 'New Delhi', lat: 28.5562, lng: 77.1000, tz: 5.5 },
  BOM: { iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj Intl', city: 'Mumbai', lat: 19.0896, lng: 72.8656, tz: 5.5 },
  BLR: { iata: 'BLR', name: 'Kempegowda Intl', city: 'Bangalore', lat: 13.1986, lng: 77.7066, tz: 5.5 },
  MAA: { iata: 'MAA', name: 'Chennai Intl', city: 'Chennai', lat: 12.9941, lng: 80.1709, tz: 5.5 },
  CCU: { iata: 'CCU', name: 'Netaji Subhas Chandra Bose Intl', city: 'Kolkata', lat: 22.6547, lng: 88.4467, tz: 5.5 },
  GOI: { iata: 'GOI', name: 'Goa Intl (Manohar)', city: 'Goa', lat: 15.3808, lng: 73.8314, tz: 5.5 },
  HYD: { iata: 'HYD', name: 'Rajiv Gandhi Intl', city: 'Hyderabad', lat: 17.2403, lng: 78.4294, tz: 5.5 },
  COK: { iata: 'COK', name: 'Cochin Intl', city: 'Kochi', lat: 10.1520, lng: 76.4019, tz: 5.5 },
  JAI: { iata: 'JAI', name: 'Jaipur Intl', city: 'Jaipur', lat: 26.8242, lng: 75.8122, tz: 5.5 },
  // International
  ZRH: { iata: 'ZRH', name: 'Zurich', city: 'Zurich', lat: 47.4582, lng: 8.5554, tz: 2 },
  SFO: { iata: 'SFO', name: 'San Francisco Intl', city: 'San Francisco', lat: 37.6191, lng: -122.375, tz: -8 },
  JFK: { iata: 'JFK', name: 'John F. Kennedy Intl', city: 'New York', lat: 40.6413, lng: -73.7781, tz: -5 },
  LHR: { iata: 'LHR', name: 'Heathrow', city: 'London', lat: 51.4700, lng: -0.4543, tz: 0 },
  HND: { iata: 'HND', name: 'Haneda', city: 'Tokyo', lat: 35.5494, lng: 139.7798, tz: 9 },
  SYD: { iata: 'SYD', name: 'Kingsford Smith', city: 'Sydney', lat: -33.9399, lng: 151.1753, tz: 10 },
  DXB: { iata: 'DXB', name: 'Dubai Intl', city: 'Dubai', lat: 25.2532, lng: 55.3657, tz: 4 },
  YVR: { iata: 'YVR', name: 'Vancouver Intl', city: 'Vancouver', lat: 49.1967, lng: -123.1815, tz: -8 },
  SIN: { iata: 'SIN', name: 'Changi', city: 'Singapore', lat: 1.3644, lng: 103.9915, tz: 8 },
  LAX: { iata: 'LAX', name: 'Los Angeles Intl', city: 'Los Angeles', lat: 33.9416, lng: -118.4085, tz: -8 },
  CDG: { iata: 'CDG', name: 'Charles de Gaulle', city: 'Paris', lat: 49.0097, lng: 2.5479, tz: 1 },
  NRT: { iata: 'NRT', name: 'Narita Intl', city: 'Tokyo', lat: 35.7720, lng: 140.3929, tz: 9 },
  ICN: { iata: 'ICN', name: 'Incheon Intl', city: 'Seoul', lat: 37.4602, lng: 126.4407, tz: 9 },
  FRA: { iata: 'FRA', name: 'Frankfurt', city: 'Frankfurt', lat: 50.0379, lng: 8.5622, tz: 1 },
  CPT: { iata: 'CPT', name: 'Cape Town Intl', city: 'Cape Town', lat: -33.9715, lng: 18.6021, tz: 2 },
  ZQN: { iata: 'ZQN', name: 'Queenstown', city: 'Queenstown', lat: -45.0211, lng: 168.7392, tz: 12 },
  KEF: { iata: 'KEF', name: 'Keflavik Intl', city: 'Reykjavik', lat: 63.9850, lng: -22.6056, tz: 0 },
  INN: { iata: 'INN', name: 'Innsbruck', city: 'Innsbruck', lat: 47.2602, lng: 11.3440, tz: 1 },
  KTM: { iata: 'KTM', name: 'Tribhuvan Intl', city: 'Kathmandu', lat: 27.6966, lng: 85.3591, tz: 5.75 },
  GIG: { iata: 'GIG', name: 'Galeao Intl', city: 'Rio de Janeiro', lat: -22.8090, lng: -43.2436, tz: -3 },
  AKL: { iata: 'AKL', name: 'Auckland', city: 'Auckland', lat: -37.0082, lng: 174.7850, tz: 12 },
  ORD: { iata: 'ORD', name: "O'Hare Intl", city: 'Chicago', lat: 41.9742, lng: -87.9073, tz: -6 },
  MIA: { iata: 'MIA', name: 'Miami Intl', city: 'Miami', lat: 25.7959, lng: -80.2870, tz: -5 },
  DOH: { iata: 'DOH', name: 'Hamad Intl', city: 'Doha', lat: 25.2731, lng: 51.6081, tz: 3 },
};

export const ROUTES = [
  // Indian domestic
  { id: 'del-bom', name: 'New Delhi → Mumbai', subtitle: "India's Busiest Corridor", origin: 'DEL', dest: 'BOM', tag: 'scenic' },
  { id: 'blr-goi', name: 'Bangalore → Goa', subtitle: 'Western Ghats Coastal', origin: 'BLR', dest: 'GOI', tag: 'scenic' },
  { id: 'del-blr', name: 'New Delhi → Bangalore', subtitle: 'North-South India', origin: 'DEL', dest: 'BLR', tag: 'sunrise' },
  { id: 'ccu-bom', name: 'Kolkata → Mumbai', subtitle: 'Cross-Country', origin: 'CCU', dest: 'BOM', tag: 'sunset' },
  { id: 'bom-cok', name: 'Mumbai → Kochi', subtitle: 'Arabian Sea Coast', origin: 'BOM', dest: 'COK', tag: 'sunset' },
  // International scenic
  { id: 'del-ktm', name: 'New Delhi → Kathmandu', subtitle: 'Himalaya Views', origin: 'DEL', dest: 'KTM', tag: 'mountain' },
  { id: 'zrh-sfo', name: 'Zurich → San Francisco', subtitle: 'Polar Route over Greenland', origin: 'ZRH', dest: 'SFO', tag: 'scenic' },
  { id: 'jfk-lhr', name: 'New York → London', subtitle: 'Transatlantic Classic', origin: 'JFK', dest: 'LHR', tag: 'sunset' },
  { id: 'syd-dxb', name: 'Sydney → Dubai', subtitle: 'Desert Sunset Chaser', origin: 'SYD', dest: 'DXB', tag: 'sunset' },
  { id: 'hnd-yvr', name: 'Tokyo → Vancouver', subtitle: 'Pacific Sunrise', origin: 'HND', dest: 'YVR', tag: 'sunrise' },
  { id: 'lax-zqn', name: 'Los Angeles → Queenstown', subtitle: 'Pacific to Mountains', origin: 'LAX', dest: 'ZQN', tag: 'scenic' },
  { id: 'lhr-sin', name: 'London → Singapore', subtitle: 'Long-Haul Overnight', origin: 'LHR', dest: 'SIN', tag: 'sunrise' },
  { id: 'jfk-kef', name: 'New York → Reykjavik', subtitle: 'Arctic Approach', origin: 'JFK', dest: 'KEF', tag: 'scenic' },
  { id: 'cdg-cpt', name: 'Paris → Cape Town', subtitle: 'African Continent', origin: 'CDG', dest: 'CPT', tag: 'sunset' },
  { id: 'icn-lax', name: 'Seoul → Los Angeles', subtitle: 'Trans-Pacific', origin: 'ICN', dest: 'LAX', tag: 'sunrise' },
];
