export const JOURNEY_ENTRIES = [
  {
    id: 1,
    phase: 'Architecture',
    title: 'Initial Stack Decision',
    timestamp: '2026-08-17T09:00:00Z',
    content: `Selected React 19 + Vite 8 as the foundation. Reasoning: React 19 offers the latest concurrent features, Vite 8 provides sub-second HMR. Considered Next.js but pure SPA is sufficient — no SSR needed for a client-side solar calculator.`,
  },
  {
    id: 2,
    phase: 'Architecture',
    title: 'UI Framework Research',
    timestamp: '2026-08-17T09:30:00Z',
    content: `Evaluated Tailwind CSS v4, shadcn/ui, Chakra UI, Aceternity UI, and HeroUI. Decision: Tailwind CSS v4 (CSS-first config) + Framer Motion. Rationale: 90% of the app is custom visualizations (seat map, solar timeline, flight map). Component libraries add dead weight for buttons we barely use. Tailwind gives precise control for the aviation HUD aesthetic.`,
  },
  {
    id: 3,
    phase: 'Design',
    title: 'Aviation HUD Noir Aesthetic',
    timestamp: '2026-08-17T10:00:00Z',
    content: `Defined "Aviation HUD Noir" design language: deep void backgrounds (oklch(0.05 0.01 260)), multi-layer glassmorphism with saturate(1.4), OKLCH color space for vibrancy, monospace data displays (JetBrains Mono), ambient aurora drift animations. Inspired by Bloomberg Terminal + flight simulator HUD.`,
  },
  {
    id: 4,
    phase: 'Implementation',
    title: 'Great Circle Path Generation',
    timestamp: '2026-08-17T10:30:00Z',
    content: `Implemented Haversine distance + spherical interpolation for great circle routes. Key insight: heading must be calculated at each waypoint locally (tangent to curve), not as the overall origin→destination bearing. Fixed by computing heading from each point to a slightly-ahead fractional point.`,
  },
  {
    id: 5,
    phase: 'Implementation',
    title: 'NOAA Solar Position Engine',
    timestamp: '2026-08-17T11:00:00Z',
    content: `Replaced basic sun approximation with proper NOAA equations: solar declination via day-of-year, Equation of Time correction, hour angle computation, and true solar elevation/azimuth from spherical trigonometry. Accuracy improved from ~30° error to <2° for azimuth.`,
  },
  {
    id: 6,
    phase: 'Implementation',
    title: 'Preference-Aware Scoring Engine',
    timestamp: '2026-08-17T11:30:00Z',
    content: `Extended seat scoring to handle 4 scenic preferences: Sunrise (weights sunrise windows 15x), Sunset (weights sunset golden hour), Shade (inverts scoring — prefers side away from sun), Scenic (balanced default with heavy sunrise/sunset weighting). Confidence calculation uses proportional difference with 20% floor.`,
  },
  {
    id: 7,
    phase: 'Implementation',
    title: 'SVG Aircraft Seat Map',
    timestamp: '2026-08-17T12:00:00Z',
    content: `Built a custom SVG aircraft fuselage with 3-3 seating (6 columns × 10 rows). Each seat is a rounded rect with Framer Motion entrance animations (staggered by row). Recommended side gets a pulsing blue glow via CSS keyframes. Port/Starboard labels with HUD-style typography.`,
  },
  {
    id: 8,
    phase: 'Implementation',
    title: 'Solar Timeline Visualization',
    timestamp: '2026-08-17T13:00:00Z',
    content: `Created horizontal timeline showing sun elevation curve across flight duration. Background gradient transitions through night→dawn→day→dusk→night. Left/right indicator band shows which side the sun is on at each waypoint. Scrubber syncs with map plane position. Built with SVG + Framer Motion.`,
  },
  {
    id: 9,
    phase: 'Iteration',
    title: 'Flight Duration from Distance',
    timestamp: '2026-08-17T13:30:00Z',
    content: `Replaced hardcoded 8-hour duration with distance-based calculation: cruise speed 885 km/h + 25min taxi/climb + 20min descent. JFK→LHR now correctly shows ~7.2h, DEL→KTM shows ~1.8h. This dramatically improves scoring accuracy for short-haul routes.`,
  },
  {
    id: 10,
    phase: 'Polish',
    title: 'Ambient Effects & Micro-Animations',
    timestamp: '2026-08-17T14:00:00Z',
    content: `Added: aurora background drift (30s CSS animation), grid pattern overlay on map panel, animated route drawing (SVG stroke-dashoffset), spring-physics tab transitions, hover glow on interactive elements, staggered panel entrance animations. Target: premium showcase feel without performance cost.`,
  },
];
